// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPrZG6sE7Fblqt1HEIirhe_D5nrJ3vZ2Y',
    appId: '1:782350910994:web:e8793a779b42dcaa443acb',
    messagingSenderId: '782350910994',
    projectId: 'docs-24287',
    authDomain: 'docs-24287.firebaseapp.com',
    databaseURL: 'https://docs-24287-default-rtdb.firebaseio.com',
    storageBucket: 'docs-24287.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJlqvvLzI71_qILqE5Z7PjYblBgaCfbsE',
    appId: '1:782350910994:android:4e024a994529b536443acb',
    messagingSenderId: '782350910994',
    projectId: 'docs-24287',
    databaseURL: 'https://docs-24287-default-rtdb.firebaseio.com',
    storageBucket: 'docs-24287.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEF6XcIPhsQtmd4f0YnVzvqamDW6ts1cI',
    appId: '1:782350910994:ios:5c82b251191bbd50443acb',
    messagingSenderId: '782350910994',
    projectId: 'docs-24287',
    databaseURL: 'https://docs-24287-default-rtdb.firebaseio.com',
    storageBucket: 'docs-24287.appspot.com',
    iosBundleId: 'com.example.googledocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEF6XcIPhsQtmd4f0YnVzvqamDW6ts1cI',
    appId: '1:782350910994:ios:060c7b511caa426d443acb',
    messagingSenderId: '782350910994',
    projectId: 'docs-24287',
    databaseURL: 'https://docs-24287-default-rtdb.firebaseio.com',
    storageBucket: 'docs-24287.appspot.com',
    iosBundleId: 'com.example.googledocs.RunnerTests',
  );
}
